name: Run Tests
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cloned repository"

  build:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

  run-tests:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
