name: Build

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]
    steps:
      - uses: actions/checkout@v4
      - run: echo "Cloned repository"

  setup-dotnet:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version

  build:
    runs-on: ubuntu-latest
    needs: setup-dotnet
    steps:
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
